fix compiler warning on Debian wheezy (gcc 4.7.2)
dumpcap.c:193:10: error: ignoring return value of ‘write’, declared with
attribute warn_unused_result [-Werror=unused-result]

for some reason, using (void)write(fd, ...) did not do the trick


git-svn-id: http://anonsvn.wireshark.org/wireshark/trunk@51476 f5534014-38df-0310-8fa8-9805f1628bb7