remove unused variable numelem
this fixes
  CC     libdissectors_la-packet-scsi-smc.lo
packet-scsi-smc.c: In function 'dissect_smc_readelementstatus':
packet-scsi-smc.c:467:11: error: variable 'numelem' set but not used
[-Werror=unused-but-set-variable]



git-svn-id: http://anonsvn.wireshark.org/wireshark/trunk@51168 f5534014-38df-0310-8fa8-9805f1628bb7